version: '3.8'

services:
  # Servicio de Tareas
  task-service:
    build:
      context: ./servicio-tareas
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/tasks"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - microservices-network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - TASKS_SERVICE_URL=http://task-service:5001
      - NODE_ENV=production
    depends_on:
      - task-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  tasks-data:
    driver: local 